[package]
name = "aoc-day13-part2"
version = "0.1.0"
authors = ["Christian Fosli <christian.fosli@capgemini.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
