name: all solutions run without crashing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run rust unit tests
        run: |
          for d in */; do
            pushd "$d"
            if [[ -f "./Cargo.toml" ]]; then
              cargo test || (touch /tmp/rustfail && printf '%s\n' "%d" >> /tmp/rustfail)
            fi
            popd
          done

          if [[ -f /tmp/rustfail ]]; then
            printf '******\n\n%d tests failed\n\n' "$(wc -l < /tmp/failures)"
            cat /tmp/rustfail
            exit 1
          fi

      - name: run fsharp interactive files
        run: |
          for d in */; do
            pushd "$d"
            for f in *.fsx; do
              if [[ -f "$f" ]]; then
                printf 'Running %s\n' "$f"
                docker run --rm -v "$(pwd):/app" mcr.microsoft.com/dotnet/sdk:5.0 \
                  /bin/bash -c "cd /app && dotnet fsi $f" \
                  || (touch /tmp/failures && printf '%s\n' "$f" >> /tmp/failures)
              fi
            done
            popd
          done

          if [[ -f /tmp/failures ]]; then
            printf '******\n\n%d tests failed\n\n' "$(wc -l < /tmp/failures)"
            cat /tmp/failures
            exit 1
          fi
