name: all solutions run without crashing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run all fsharp interactive files
        run: |
          for d in */; do
            pushd "$d"
            for f in *.fsx; do
              printf 'Running %s\n' "$f"
              docker run --rm -v "$(pwd):/app" mcr.microsoft.com/dotnet/sdk:5.0 \
                /bin/bash -c "cd /app && dotnet fsi $f"
            done
            popd
          done
